version: '3'

services:
  influxdb:
    # https://hub.docker.com/_/influxdb/
    container_name: influxdb
    image: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - influxdb.env
    restart: unless-stopped
    networks:
      - backend
      - frontend

  redis:
    # https://hub.docker.com/_/redis/
    container_name: redis
    image: redis
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - redis.env
    restart: unless-stopped
    networks:
      - backend

  chronograf:
    # https://hub.docker.com/_/chronograf/
    container_name: chronograf
    image: chronograf
    ports:
      - 8888:8888
    volumes:
      - chronograf:/var/lib/chronograf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - chronograf.env
    command: chronograf --influxdb-url=http://influxdb:8086
    depends_on:
      - influxdb
    restart: unless-stopped
    networks:
      - backend
      - frontend
      - nginx

  mqtt2influxdb:
    container_name: mqtt2influxdb
    image: davidlor/python-autoclonable-app:latest-dev
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - REDIS_HOST=redis
      - INFLUX_HOST=influxdb
    env_file:
      - mqtt2influxdb.env
    depends_on:
      - influxdb
      - redis
    networks:
      - backend
      - frontend

networks:
  frontend:
    driver: bridge
    internal: false
  backend:
    driver: bridge
    internal: true

volumes:
  influxdb:
  chronograf:
